// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxztvtjtkyuqrmzwuaax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14enR2dGp0a3l1cXJtend1YWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDUzOTksImV4cCI6MjA1OTk4MTM5OX0.3yJUW2dbyvJRv0JoV4vPBmqGblNggGEEbmq4Ev9-T0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);